#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Nov 29 12:18:21 2022

@author: elipage
"""

import uuid

for i in range(1,10):

    myuuid = uuid.uuid4()

    print('Your UUID is: ' + str(myuuid))

